set(CGO_GENERATED_DIR "${CMAKE_BINARY_DIR}/cgo_generated")

# Generates the unity include list for a module: one entry per .cpp, each
# preceded by a path-derived ANON name. EXCLUDE names directories to skip.
function(cgo_generate_units module)
    cmake_parse_arguments(ARG "" "" "EXCLUDE" ${ARGN})

    set(module_path "${CMAKE_CURRENT_SOURCE_DIR}/${module}")

    file(GLOB_RECURSE units CONFIGURE_DEPENDS "${module_path}/*.cpp")
    list(FILTER units EXCLUDE REGEX "/${module}\\.cpp$")

    foreach(dir IN LISTS ARG_EXCLUDE)
        list(FILTER units EXCLUDE REGEX "/${dir}/")
    endforeach()

    list(SORT units)

    if(NOT units)
        message(FATAL_ERROR "cgo_generate_units: no units in ${module}")
    endif()

    set(content "// Generated by cgo_generate_units(). Do not edit.\n\n")

    foreach(unit IN LISTS units)
        file(RELATIVE_PATH rel "${module_path}" "${unit}")
        string(REGEX REPLACE "[^A-Za-z0-9]" "_" name "${rel}")
        string(APPEND content "#undef ANON\n" "#define ANON cgoAnon_${name}\n" "#include <${module}/${rel}>\n\n")
    endforeach()

    string(APPEND content "#undef ANON\n")
    file(GENERATE OUTPUT "${CGO_GENERATED_DIR}/${module}_units.inc" CONTENT "${content}")
endfunction()
